#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../../lib/relay"
require File.join(Relay.root, "app", "init")

warn "relay: download models"
Relay::Models::ModelRecord.refresh_all
